name: cruising
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path_provider: ^2.1.5
  window_manager: ^0.5.1
  audioplayers: ^6.1.0
  win32: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/gameicon.png"
  min_sdk_android: 21 # android min sdk value
  web:
    generate: true
    image_path: "assets/images/icon/gameicon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/icon/gameicon.png"
    icon_size: 256 # min:48, max:256, default: 256
  macos:
    generate: true
    image_path: "assets/images/icon/gameicon.png"
  linux:
    generate: true
    image_path: "assets/images/icon/gameicon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/config/
    - assets/images/
    - assets/images/background/
    - assets/images/buildings/
    - assets/images/painting/
    - assets/images/ships/
    - assets/images/avatar/
    - assets/images/goods/
    - assets/paper_ui/Sprites/Book Desk/
    - assets/paper_ui/Sprites/Content/4_Buttons/
    - assets/paper_ui/Sprites/Content/5_Holders/
    - assets/paper_ui/Sprites/Content/3_Progress_Bars/
    - assets/music/main_menu/
    - assets/music/combat/
    - assets/music/cruising/
    - assets/sfx/button_press/
    - assets/sfx/panel_open/
    - assets/sfx/seagull/
    - assets/sfx/wave/